### ISSUE TITLE
textContent vs. innerHTML

### ISSUE THREAD

**Issue by jphager2** [pakyow/pakyow-js#1]
In pakyow.js, when binding a value to the document, is it possible to use `innerHTML` instead of `textContent`, so that html can be sent as content from the binding and rendered properly in the browser?

This is the line I would propose changing (pakyow.js:320):

```
pw.node.isSelfClosingTag(doc) ? doc.value = value : doc.textContent = value
```

**Comment by bryanp** [comment]
Somehow I missed this issue. If we make this change we'd also have to make it on the backend to be consistent. I believe that it uses `text` currently rather than `html`. Could be wrong.

In general though I am not opposed to this. Do you have a specific use case that led to this?

**Comment by jphager2** [comment]
Yeah so in the bindings, I pass html to the content key. So it works well
when rendered with string doc, but via pakyow-js, the html is rendered as
plain text.

I guess maybe this is because in `View#bind_value_to_doc` the value is set
to the doc via the html method. Not sure.

**Comment by bryanp** [comment]
Sorry, I wasn't clear. Really what I am after here is a valid use-case for why you'd want to render HTML from a binding :-)

**Comment by jphager2** [comment]
Oh yeah. So i am using using mark up that is saved in an article model and
rendered as html in the bindings. So i guess the use case is realtime
updates in a content management system. (I guess it might not be a great
case for pakyow-ui, but it would be nice if it is supported)

**Comment by bryanp** [comment]
Cool, I am okay with this.

**Comment by bryanp** [comment]
Fixed in this commit: https://github.com/pakyow/pakyow-js/commit/4b9c03d9463d6fe1f296e9dceaa1a25ecf9345d8
